export const REPORT_SCHEMA_VERSION = "1.0.0" as const;

export const PROVENANCE_KIND = {
  OBSERVED: "observed",
  INFERRED: "inferred",
  USER_DECLARED: "user_declared",
  UNKNOWN: "unknown",
} as const;

export const FINDING_CATEGORY = {
  ARCHITECTURE: "architecture",
  SECURITY: "security",
  AI_SECURITY: "ai_security",
} as const;

export const FINDING_STATUS = {
  CODE_SUPPORTED: "code_supported_weakness",
  PLAUSIBLE_THREAT: "plausible_threat_requiring_verification",
  ARCHITECTURE_CONCERN: "architecture_concern",
  INSUFFICIENT_EVIDENCE: "insufficient_evidence",
} as const;

export const FINDING_LIFECYCLE = {
  OPEN: "open",
  FIXED: "fixed",
  REGRESSED: "regressed",
} as const;

export const FINDING_LIFECYCLE_LIST = [
  FINDING_LIFECYCLE.OPEN,
  FINDING_LIFECYCLE.FIXED,
  FINDING_LIFECYCLE.REGRESSED,
] as const;

export const FINDING_DISPOSITION = {
  UNREVIEWED: "unreviewed",
  CONFIRMED: "confirmed",
  FALSE_POSITIVE: "false_positive",
  ACCEPTED_RISK: "accepted_risk",
} as const;

export const FINDING_DISPOSITION_LIST = [
  FINDING_DISPOSITION.UNREVIEWED,
  FINDING_DISPOSITION.CONFIRMED,
  FINDING_DISPOSITION.FALSE_POSITIVE,
  FINDING_DISPOSITION.ACCEPTED_RISK,
] as const;

export const SOURCE_LANGUAGE = {
  JAVASCRIPT: "javascript",
  PYTHON: "python",
  GO: "go",
  HTML: "html",
  YAML: "yaml",
  SQL: "sql",
  SHELL: "shell",
} as const;

export const SOURCE_LANGUAGE_LIST = [
  SOURCE_LANGUAGE.JAVASCRIPT,
  SOURCE_LANGUAGE.PYTHON,
  SOURCE_LANGUAGE.GO,
  SOURCE_LANGUAGE.HTML,
  SOURCE_LANGUAGE.YAML,
  SOURCE_LANGUAGE.SQL,
  SOURCE_LANGUAGE.SHELL,
] as const;

export const CWE_ID = {
  PATH_TRAVERSAL: "CWE-22",
  IMPROPER_VERIFICATION: "CWE-347",
  DESERIALIZATION: "CWE-502",
  COMMAND_INJECTION: "CWE-78",
  XSS: "CWE-79",
  SQL_INJECTION: "CWE-89",
  CODE_INJECTION: "CWE-94",
  MISSING_AUTHENTICATION: "CWE-306",
  WEAK_CRYPTO: "CWE-327",
  INSUFFICIENT_RANDOM: "CWE-330",
  SENSITIVE_COOKIE: "CWE-614",
  HARDCODED_CREDENTIAL: "CWE-798",
  SSRF: "CWE-918",
  UNNECESSARY_PRIVILEGES: "CWE-250",
} as const;

export const CWE_ID_LIST = [
  CWE_ID.PATH_TRAVERSAL,
  CWE_ID.IMPROPER_VERIFICATION,
  CWE_ID.DESERIALIZATION,
  CWE_ID.COMMAND_INJECTION,
  CWE_ID.XSS,
  CWE_ID.SQL_INJECTION,
  CWE_ID.CODE_INJECTION,
  CWE_ID.MISSING_AUTHENTICATION,
  CWE_ID.WEAK_CRYPTO,
  CWE_ID.INSUFFICIENT_RANDOM,
  CWE_ID.SENSITIVE_COOKIE,
  CWE_ID.HARDCODED_CREDENTIAL,
  CWE_ID.SSRF,
  CWE_ID.UNNECESSARY_PRIVILEGES,
] as const;

export const DATA_FLOW_ROLE = {
  SOURCE: "source",
  CALL: "call",
  SINK: "sink",
} as const;

export const DATA_FLOW_ROLE_LIST = [
  DATA_FLOW_ROLE.SOURCE,
  DATA_FLOW_ROLE.CALL,
  DATA_FLOW_ROLE.SINK,
] as const;

export const STRIDE_CATEGORY = {
  SPOOFING: "spoofing",
  TAMPERING: "tampering",
  REPUDIATION: "repudiation",
  INFORMATION_DISCLOSURE: "information_disclosure",
  DENIAL_OF_SERVICE: "denial_of_service",
  ELEVATION_OF_PRIVILEGE: "elevation_of_privilege",
} as const;

export const OWASP_CATEGORY = {
  BROKEN_ACCESS_CONTROL: "A01:2021",
  CRYPTOGRAPHIC_FAILURES: "A02:2021",
  INJECTION: "A03:2021",
  INSECURE_DESIGN: "A04:2021",
  SECURITY_MISCONFIGURATION: "A05:2021",
  VULNERABLE_COMPONENTS: "A06:2021",
  AUTHENTICATION_FAILURES: "A07:2021",
  INTEGRITY_FAILURES: "A08:2021",
  LOGGING_FAILURES: "A09:2021",
  SSRF: "A10:2021",
  LLM_PROMPT_INJECTION: "LLM01:2025",
  LLM_SENSITIVE_DISCLOSURE: "LLM02:2025",
  LLM_SUPPLY_CHAIN: "LLM03:2025",
  LLM_DATA_POISONING: "LLM04:2025",
  LLM_IMPROPER_OUTPUT: "LLM05:2025",
  LLM_EXCESSIVE_AGENCY: "LLM06:2025",
  LLM_SYSTEM_PROMPT_LEAKAGE: "LLM07:2025",
  LLM_VECTOR_WEAKNESSES: "LLM08:2025",
  LLM_MISINFORMATION: "LLM09:2025",
  LLM_UNBOUNDED_CONSUMPTION: "LLM10:2025",
} as const;

export const OWASP_CATEGORY_LIST = [
  OWASP_CATEGORY.BROKEN_ACCESS_CONTROL,
  OWASP_CATEGORY.CRYPTOGRAPHIC_FAILURES,
  OWASP_CATEGORY.INJECTION,
  OWASP_CATEGORY.INSECURE_DESIGN,
  OWASP_CATEGORY.SECURITY_MISCONFIGURATION,
  OWASP_CATEGORY.VULNERABLE_COMPONENTS,
  OWASP_CATEGORY.AUTHENTICATION_FAILURES,
  OWASP_CATEGORY.INTEGRITY_FAILURES,
  OWASP_CATEGORY.LOGGING_FAILURES,
  OWASP_CATEGORY.SSRF,
  OWASP_CATEGORY.LLM_PROMPT_INJECTION,
  OWASP_CATEGORY.LLM_SENSITIVE_DISCLOSURE,
  OWASP_CATEGORY.LLM_SUPPLY_CHAIN,
  OWASP_CATEGORY.LLM_DATA_POISONING,
  OWASP_CATEGORY.LLM_IMPROPER_OUTPUT,
  OWASP_CATEGORY.LLM_EXCESSIVE_AGENCY,
  OWASP_CATEGORY.LLM_SYSTEM_PROMPT_LEAKAGE,
  OWASP_CATEGORY.LLM_VECTOR_WEAKNESSES,
  OWASP_CATEGORY.LLM_MISINFORMATION,
  OWASP_CATEGORY.LLM_UNBOUNDED_CONSUMPTION,
] as const;

export const ATLAS_TECHNIQUE = {
  POISON_TRAINING_DATA: "AML.T0020",
  LLM_PROMPT_INJECTION: "AML.T0051",
  AI_AGENT_TOOL_INVOCATION: "AML.T0053",
  LLM_JAILBREAK: "AML.T0054",
  UNSECURED_CREDENTIALS: "AML.T0055",
  EXTRACT_LLM_SYSTEM_PROMPT: "AML.T0056",
  LLM_DATA_LEAKAGE: "AML.T0057",
  RAG_POISONING: "AML.T0070",
} as const;

export const ATLAS_TECHNIQUE_LIST = [
  ATLAS_TECHNIQUE.POISON_TRAINING_DATA,
  ATLAS_TECHNIQUE.LLM_PROMPT_INJECTION,
  ATLAS_TECHNIQUE.AI_AGENT_TOOL_INVOCATION,
  ATLAS_TECHNIQUE.LLM_JAILBREAK,
  ATLAS_TECHNIQUE.UNSECURED_CREDENTIALS,
  ATLAS_TECHNIQUE.EXTRACT_LLM_SYSTEM_PROMPT,
  ATLAS_TECHNIQUE.LLM_DATA_LEAKAGE,
  ATLAS_TECHNIQUE.RAG_POISONING,
] as const;

export const RISK_DOMAIN = {
  CYBERSECURITY: "cybersecurity",
  DATA: "data",
  INFRASTRUCTURE: "infrastructure",
  AI_EXECUTION: "ai_execution",
} as const;

export const RISK_DOMAIN_LIST = [
  RISK_DOMAIN.CYBERSECURITY,
  RISK_DOMAIN.DATA,
  RISK_DOMAIN.INFRASTRUCTURE,
  RISK_DOMAIN.AI_EXECUTION,
] as const;

export const AUDIT_AGENT = {
  CARTOGRAPHER: "cartographer",
  CODE_READER: "code_reader",
  STRIDE: "stride",
  OWASP: "owasp",
  ATLAS: "atlas",
  DATA: "data",
  INFRASTRUCTURE: "infrastructure",
  PULL_REQUEST: "pull_request",
  VERIFIER: "verifier",
} as const;

export const AUDIT_AGENT_ORDER = [
  AUDIT_AGENT.CODE_READER,
  AUDIT_AGENT.CARTOGRAPHER,
  AUDIT_AGENT.STRIDE,
  AUDIT_AGENT.OWASP,
  AUDIT_AGENT.ATLAS,
  AUDIT_AGENT.DATA,
  AUDIT_AGENT.INFRASTRUCTURE,
  AUDIT_AGENT.PULL_REQUEST,
  AUDIT_AGENT.VERIFIER,
] as const;

export const COPILOT_SKILL = {
  ACCURACY: "accuracy",
  FULL_REPOSITORY: "full_repository",
  THREAT_MODEL: "threat_model",
  PULL_REQUEST: "pull_request",
  MEMORY: "memory",
} as const;

export const AGENT_RUN_STATUS = {
  COMPLETED: "completed",
  SKIPPED: "skipped",
  FAILED: "failed",
} as const;

export const GRAPH_NODE_KIND = {
  ACTOR: "actor",
  APPLICATION: "application",
  SERVICE: "service",
  MODULE: "module",
  API_ENTRY: "api_entry",
  DATA_STORE: "data_store",
  QUEUE: "queue",
  WORKER: "worker",
  EXTERNAL_SYSTEM: "external_system",
  AI_MODEL: "ai_model",
  AI_AGENT: "ai_agent",
  AI_TOOL: "ai_tool",
  RETRIEVAL_STORE: "retrieval_store",
  MEMORY: "memory",
  TRUST_BOUNDARY: "trust_boundary",
  FUNCTION: "function",
} as const;

export const ANALYSIS_MODE = {
  BROWSER: "browser",
  DEEP_RUNNER: "deep_runner",
  IMPORTED: "imported",
} as const;

export const PROVIDER_ID = {
  OPENAI: "openai",
  ANTHROPIC: "anthropic",
  GEMINI: "gemini",
  DEEPSEEK: "deepseek",
  OPENAI_COMPATIBLE: "openai_compatible",
} as const;
